name: E2E Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/web-app/package-lock.json
        env:
          NODE_OPTIONS: '--max_old_space_size=4096'

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start backend server
        working-directory: ./backend
        run: |
          # Initialize database if needed
          python -m alembic upgrade head || echo "No migrations to run"
          # Ensure all tables are created (in case migrations are incomplete)
          python init_db.py
          # Verify database was created
          ls -la test_hermes.db || echo "Database file not found"
          # Start backend in background
          uvicorn main:app --host 0.0.0.0 --port 8000 &
          # Wait for backend to be ready
          echo "Waiting for backend to start..."
          timeout 60 bash -c 'until curl -s http://localhost:8000/health > /dev/null 2>&1; do echo "Waiting..."; sleep 2; done'
          # Test the projects endpoint specifically
          echo "Testing projects endpoint..."
          curl -v http://localhost:8000/api/v1/projects/ || echo "Projects endpoint failed"
        env:
          DATABASE_URL: sqlite:///./test_hermes.db

      - name: Install frontend dependencies
        working-directory: ./frontend/web-app
        run: npm ci --legacy-peer-deps

      - name: Build frontend
        working-directory: ./frontend/web-app
        run: DISABLE_ESLINT_PLUGIN=true REACT_APP_API_URL=http://localhost:8000 npm run build

      - name: Start frontend server
        working-directory: ./frontend/web-app
        run: |
          npx serve -s build -l 3000 &
          # Wait for frontend to be ready
          timeout 60 bash -c 'until curl -s http://localhost:3000 > /dev/null 2>&1; do sleep 2; done'

      - name: Install Chrome for testing
        run: |
          wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run E2E tests
        working-directory: ./frontend/web-app
        run: npx cypress run --browser chrome --headless
        env:
          CYPRESS_baseUrl: http://localhost:3000
          CYPRESS_apiUrl: http://localhost:8000
          NODE_OPTIONS: '--max_old_space_size=4096'

      - name: Upload Cypress screenshots on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: frontend/web-app/cypress/screenshots
          retention-days: 7

      - name: Upload Cypress videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: frontend/web-app/cypress/videos
          retention-days: 7

      - name: Upload Cypress test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-reports
          path: frontend/web-app/cypress/results
          retention-days: 30
